--1 total revenue generated by male vs female
select gender , SUM(purchase_amount) as revenue
from customer
group by gender

--2 customer used discount but still spend more then avg
select customer_id, purchase_amount 
from customer
where discount_applied = 'Yes' and purchase_amount >={select AVG(purchase_amount from)}

--3 Subscribed customer spend more or non subscribed
select subscription,
COUNT(customer_id) as total_customers,
ROUND(AVG (purchase_amount),2) as avg_spend,
round(SUM(purchase_amount)) as total_revenue
from customer
group by subscription
order by total_revenue,avg_spend desc;

--4 top 5 product with highest percentage discount applied
select item_purchase,
round(100 * SUM(CASE when discount_applied = 'YES' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchase
order by discount_rate desc
limit 5;


--5 segment customer into new , loyal etc.....
with customer_type as (
select customer_id , prvious_purchases,
case 
when prvious_purchases between 1 and 9 then 'New'
when prvious_purchases between 10 and 30 then 'Returning'
else 'LOYAL'
end as customer_segment
from customer
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

-- 6 top 3 most purchased item
with item_counts as(
select category,
item_purchased,
count(customer_id) as total_orders
)

--7 customer who are repeat buyers are subscribed or not?
select subscription,
count (customer_id) as repeat_buyers
from customer
where prvious_purchases > 10
group by subscription

--8 revenue contribution by age group
select age_group,
sum(purchase_amount)as total_revenue
from customer
group by age_group
order by total_revenue desc;

select * from customer limit 20